### PR TITLE
Typo errors in project documentation #71

### LINKED ISSUE #71: Typo errors in project documentation
image

##  Welcome to NodeCloud with [Hacktoberfest 2020](https://hacktoberfest.digitalocean.com/)! 
**Stay in the know:** Get notified of updates by clicking the 👁‍🗨 watch button and save the repository for later reference by clicking the ⭐️ star button at the top right corner of this repo! 

### Some typo errors need to be fixed:

The `readme` [file](https://github.com/leopardslab/nodecloud/blob/nodecloud-next/README.md) of the `nodecloud-next` branch contains some typo errors. To note some (**typo error > correction**),

*  NodeCloud ☁️ is standard library >  NodeCloud ☁️ is  a standard library
*  providers with less code changes > providers with fewer code changes
* open source >  open-source
* community driven plugin > community-driven plugin,
* third party > third-party
* background knowlege on these > background knowledge on these
* This is where magic happens✨ > This is where the magic happens✨
* automactically  > automatically
*  immediatly > immediately 

These need to be corrected and if you identify more typo errors while reading, fix them as well. Feel free to add a comment for further clarifications!

### Additional information

* The project currently contains two main branches: `master` and `nodecloud-next`. **This feature is required to the `nodecloud-next` branch. so make sure that you create the feature branch from `nodecloud-next`.** 

**`nodecloud-next:`** https://github.com/leopardslab/nodecloud/tree/nodecloud-next.

* Be sure to sign up at https://hacktoberfest.digitalocean.com so you can qualify to pick a limited edition t-shirt 👚 or plant a tree 🌳!

* See https://hacktoberfest.digitalocean.com for more details.

* Add a comment below if you are interested, will assign the task.

### Impact

*  Read me file

## Knowledge required 

* Version control systems (git)

### PR DESCRIPTION
**Pull request by ZenVega**
Fixes #71 

* Checked readme for typos and spelling mistakes

### CODE REVIEW

**Comment by rajitha1998** [comment]
Thank you for this! Could you actually do some changes in this pull request @ZenVega,

* The commit message you have added is `add husky `, this might confuse developers in the future as the main change here is `Fixing typos in the project documentation`. It would be great if you can fix this.

*  Just to clarify, hope you used the command `yarn add husky --dev -W` when adding the package.

**Comment by ZenVega** [comment]
Hey @rajitha1998 , yes, that's what I did. And like you said I made a new commit with a proper message and pushed all branches wit 'git push --all origin ' but it doesn't seem to update the PR. Do you have an explanation? shall ich start a new one?

**Comment by rajitha1998** [comment]
> Hey @rajitha1998 , yes, that's what I did. And like you said I made a new commit with a proper message and pushed all branches wit 'git push --all origin ' but it doesn't seem to update the PR. Do you have an explanation? shall ich start a new one?

Yes, it hasn't reflected in the pull request. No need of pushing it to all branches, what you need to do is pushing it to the branch that you worked on. Now what you can do is amending the commit message you have added. 

More info: https://docs.github.com/en/free-pro-team@latest/github/committing-changes-to-your-project/changing-a-commit-message#:~:text=On%20the%20command%20line%2C%20navigate,message%2C%20and%20save%20the%20commit.

**Comment by ZenVega** [comment]
Well, I think I got it😅

**Comment by rajitha1998** [comment]
> Well, I think I got it😅

Seems like you have added multiple commits with the same name.  I think it's better to do a soft reset and commit your files fresh. Afterwards, force push to your branch. @ZenVega

tempsnip

**Comment by ZenVega** [comment]
oh boy, git is messing with me. but it seems right now, doesn't it?

**Comment by rajitha1998** [comment]
Thank you for your contribution to the [SCoRe Lab community](https://gitter.im/scorelab/scorelab) @ZenVega.

**Pull request merged**
