### PR TITLE
Taking Codacy suggestions into account #16

### LINKED ISSUE #16: Codacy changes
Take Codacy suggestions into account and make necessary changes to improve the code quality.

### PR DESCRIPTION
**Pull request by rajitha1998**
Fixes #16 

## Proposed Changes
  - This PR adds some Codacy suggestions in order to improve code quality

### CODE REVIEW

**Review by rajikaimal — COMMENTED** [review]
@rajitha1998 did you use Prettier to format?

**Comment by rajitha1998** [comment]
No, I haven't use prettier to format. Shall I format the code using `Prettier` ? @rajikaimal 


* By the way some suggestions under the category of `Error Prone` which I assume that the console logs were added to display the output of this example or to display an error message. So I didn't remove them.
E.g. -
Capture


* I also assumed that the security issue by using a Found non-literal argument in require in this scenario should be ignored `const ncConfig = require(path.join(process.cwd(), ".nc.config"));`
Capture

**Comment by rajikaimal** [comment]
@rajitha1998 Yes, use Prettier to format all the files.

**Comment by rajitha1998** [comment]
@rajikaimal , I formatted the code using prettier.  Since **codacy** was showing me the below suggestion I had to add a prettier rule for that in the `.prettierrc` file as `{ "arrowParens": "always" }`

```
// Bad 
a => {
}
// Good 
(a) => {
}
```
Related links -
* https://prettier.io/docs/en/options.html
* https://github.com/prettier/prettier/issues/812
* https://github.com/prettier/prettier/pull/3324

**Comment by rajikaimal** [comment]
@rajitha1998 Can you resolve the conflict. LGTM

**Review by rajikaimal — APPROVED** [review]

**Comment by rajitha1998** [comment]
> @rajitha1998 Can you resolve the conflict. LGTM

sure

**Comment by rajitha1998** [comment]
Merge conflicts fixed @rajikaimal  ☺️

**Pull request closed without merging**
