### PR TITLE
Saving generated class files to their specific folders

### PR DESCRIPTION
**Pull request by mbcse**
Fixes #

## Proposed Changes

 - Class files of different services that were generated were stored in the same folder
  - Made a helper function in lib to map a service name to the dir to which it should get stored 
  - Used the function in generator to get directory name before saving the files 
  - More services can be added easily by just putting the name of service in the respective directory array object defined in lib/herper.ts

### CODE REVIEW

**Review by rajitha1998 — CHANGES_REQUESTED** [review]
Have you formatted the code before making the PR? You can run prettier either using Lerna or Yarn. @mbcse

**Comment by mbcse** [comment]
> Have you formatted the code before making the PR? You can run prettier either using Lerna or Yarn. @mbcse

Sorry, I thought it would be done automatically. I have done the same now @rajitha1998

**Review by rajitha1998 — APPROVED** [review]
LGTM :)

**Comment by mbcse** [comment]
Merged in #96

**Pull request closed without merging**
