### PR TITLE
Writing Google Cloud  AutoML examples

### PR DESCRIPTION
**Pull request by rajitha1998**
Related Issue #42

## Proposed Changes

  - Writing examples for Google cloud Auto ML service

### CODE REVIEW

**Comment by rajikaimal** [comment]
What's the equivalent in AWS? @rajitha1998

**Comment by rajitha1998** [comment]
> What's the equivalent in AWS? @rajitha1998

In AWS the equivalent service is [sagemaker](https://aws.amazon.com/sagemaker/)  and in Azure it is [AutomatedML](https://azure.microsoft.com/en-us/services/machine-learning/automatedml/)

**Comment by rajikaimal** [comment]
Do they have equivalent functionalities/APIs in Sagemaker, AutoML and AutomatedML?

**Comment by rajitha1998** [comment]
They all have common functionalities like creating models, deploying models, training models, creating datasets etc. But currently Azure does not provide a Nodejs SDK for AutomatedML.  @rajikaimal 

References 
* https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SageMaker.html
* https://googleapis.dev/nodejs/automl/latest/
* https://docs.microsoft.com/en-us/azure/machine-learning/how-to-use-automated-ml-for-ml-models

**Pull request merged**
